---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  creationTimestamp: null
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: service1
  namespace: default
spec:
  source:
    subPath: service1
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/subpathtester
status:
  supplyChainRef: {}
